apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # Helm 的 b64enc 函式會自動把 values 的字串轉成 Base64
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}