apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: {{ include "grafana.lokiUrl" . }}
        isDefault: true
        editable: true
        jsonData:
          maxLines: 1000
          derivedFields: []
  {{- if .Values.prometheus.enabled }}
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: {{ include "grafana.prometheusUrl" . }}
        isDefault: false
        editable: true
        jsonData:
          timeInterval: 15s
  {{- end }}
