from typing import Protocol, List, Tuple

class DataMerger(Protocol):
    def merge_single(self, code: str, candle: str) -> None: ...
    def batch_merge(self, task_list: List[Tuple[str, str]]) -> None: ...
    def merge_all_available_data(self) -> None: ...
    def close(self) -> None: ...