{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics.kubeStateMetrics.fullname" . }}
  labels:
    {{- include "metrics.kubeStateMetrics.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "metrics.kubeStateMetrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metrics.kubeStateMetrics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "metrics.kubeStateMetrics.fullname" . }}
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      {{- end }}
      {{- with .Values.kubeStateMetrics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kube-state-metrics
          image: "{{ .Values.kubeStateMetrics.image.repository }}:{{ .Values.kubeStateMetrics.image.tag }}"
          imagePullPolicy: {{ .Values.kubeStateMetrics.image.pullPolicy }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.kubeStateMetrics.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http-metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-metrics
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            {{- toYaml .Values.kubeStateMetrics.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
{{- end }}
