{{- if .Values.prometheus.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metrics.prometheus.fullname" . }}-data
  labels:
    {{- include "metrics.prometheus.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
{{- end }}
