CREATE TYPE "task_status" AS ENUM (
  'pending',
  'running',
  'completed',
  'failed'
);

CREATE TYPE "trigger_type" AS ENUM (
  'scheduled',
  'manual'
);

CREATE TABLE "task_event" (
  "id" uuid PRIMARY KEY,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "status" task_status NOT NULL DEFAULT 'pending',
  "tester_name" varchar(100),
  "tester_params" jsonb,
  "data_provider_name" varchar(100),
  "source_meta_data" jsonb,
  "tpsl_name" varchar(100),
  "tpsl_params" jsonb,
  "saver_params" jsonb,
  "trigger_type" trigger_type NOT NULL,
  "triggered_by" varchar(100) NOT NULL,
  "schedule_id" varchar(100),
  "schedule_name" varchar(200),
  "start_time" timestamp,
  "end_time" timestamp,
  "error_message" text
);

CREATE INDEX "idx_task_event_status" ON "task_event" ("status");

CREATE INDEX "idx_task_event_tester_name" ON "task_event" ("tester_name");

CREATE INDEX "idx_task_event_created_at" ON "task_event" ("created_at");

CREATE INDEX "idx_task_event_trigger_type" ON "task_event" ("trigger_type");

CREATE INDEX "idx_task_event_triggered_by" ON "task_event" ("triggered_by");

COMMENT ON COLUMN "task_event"."id" IS 'UUID generated by backend';

COMMENT ON COLUMN "task_event"."triggered_by" IS 'User ID or system ID who triggered the task';

COMMENT ON COLUMN "task_event"."schedule_id" IS 'Reference to schedule if triggered by scheduler';