CREATE TABLE "backtest_scheduler_task" (
  "id" uuid PRIMARY KEY,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "tester_name" varchar(100) NOT NULL,
  "tester_params" jsonb NOT NULL,
  "data_provider_name" varchar(100) NOT NULL,
  "code" varchar(30) NOT NULL,
  "candle" candle_stick NOT NULL,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "tpsl_name" varchar(100) NOT NULL,
  "tpsl_params" jsonb NOT NULL,
  "saver_params" jsonb NOT NULL
);

COMMENT ON COLUMN "backtest_scheduler_task"."id" IS 'UUID generated by backend';