CREATE TABLE "log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" timestamp NOT NULL DEFAULT (now()),
  "module" varchar(100) NOT NULL,
  "action" varchar(100) NOT NULL,
  "message" text NOT NULL,
  "level" varchar(20) NOT NULL,
  "user_id" varchar(50),
  "ip_address" varchar(45),
  "user_agent" text,
  "request_id" varchar(50),
  "duration" int,
  "status_code" int,
  "error_details" text,
  "request_method" varchar(10),
  "request_path" varchar(255),
  "response_size" int,
  "metadata" jsonb
);

CREATE INDEX log_timestame_level_idx ON "log" ("timestamp", "level");

CREATE INDEX log_module_action_idx  ON "log" ("module", "action");

CREATE INDEX log_userid_idx ON "log" ("user_id");

CREATE INDEX log_requestid_idx ON "log" ("request_id");

CREATE INDEX log_requestpath_idx ON "log" ("request_path");